# Generated by Django 6.1 on 2026-09-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=255)),
                ('total_grid_kwh', models.FloatField()),
                ('total_cost_bdt', models.FloatField()),
                ('peak_grid_kwh', models.FloatField()),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
